(function(){'use strict';
'use strict';var e="object"===typeof __ScalaJSEnv&&__ScalaJSEnv?__ScalaJSEnv:{},k="object"===typeof e.global&&e.global?e.global:"object"===typeof global&&global&&global.Object===Object?global:this;e.global=k;var m="object"===typeof e.exportsNamespace&&e.exportsNamespace?e.exportsNamespace:k;e.exportsNamespace=m;k.Object.freeze(e);var p={envInfo:e,semantics:{asInstanceOfs:2,arrayIndexOutOfBounds:2,moduleInit:2,strictFloats:!1,productionMode:!0},assumingES6:!1,linkerVersion:"0.6.28",globalThis:this};
k.Object.freeze(p);k.Object.freeze(p.semantics);var r=k.Math.imul||function(a,b){var c=a&65535,d=b&65535;return c*d+((a>>>16&65535)*d+c*(b>>>16&65535)<<16>>>0)|0},t=k.Math.clz32||function(a){if(0===a)return 32;var b=1;0===(a&4294901760)&&(a<<=16,b+=16);0===(a&4278190080)&&(a<<=8,b+=8);0===(a&4026531840)&&(a<<=4,b+=4);0===(a&3221225472)&&(a<<=2,b+=2);return b+(a>>31)},u=0,v=k.WeakMap?new k.WeakMap:null;
function w(a){return function(b,c){return!(!b||!b.$classData||b.$classData.k!==c||b.$classData.i!==a)}}function aa(a){for(var b in a)return b}function x(a,b,c){var d=new a.B(b[c]);if(c<b.length-1){a=a.l;c+=1;for(var h=d.z,g=0;g<h.length;g++)h[g]=x(a,b,c)}return d}
function ba(a){switch(typeof a){case "string":return y(z);case "number":var b=a|0;return b===a?A(b)?y(B):C(b)?y(D):y(E):"number"===typeof a?y(F):y(H);case "boolean":return y(I);case "undefined":return y(ca);default:return null===a?a.T():a&&a.$classData&&a.$classData.f.x?y(da):a&&a.$classData?y(a.$classData):null}}
function ea(a){switch(typeof a){case "string":fa||(fa=(new J).d());for(var b=0,c=1,d=-1+(a.length|0)|0;0<=d;)b=b+r(65535&(a.charCodeAt(d)|0),c)|0,c=r(31,c),d=-1+d|0;return b;case "number":K||(K=(new L).d());b=K;c=a|0;if(c===a&&-Infinity!==1/a)b=c;else{if(b.g)b.C[0]=a,b=M(b.r[b.E]|0,b.r[b.D]|0);else{if(a!==a)b=!1,a=2047,c=+k.Math.pow(2,51);else if(Infinity===a||-Infinity===a)b=0>a,a=2047,c=0;else if(0===a)b=-Infinity===1/a,c=a=0;else if(d=(b=0>a)?-a:a,d>=+k.Math.pow(2,-1022)){a=+k.Math.pow(2,52);c=
+k.Math.log(d)/.6931471805599453;c=+k.Math.floor(c)|0;c=1023>c?c:1023;var h=+k.Math.pow(2,c);h>d&&(c=-1+c|0,h/=2);h=d/h*a;d=+k.Math.floor(h);h-=d;d=.5>h?d:.5<h?1+d:0!==d%2?1+d:d;2<=d/a&&(c=1+c|0,d=1);1023<c?(c=2047,d=0):(c=1023+c|0,d-=a);a=c;c=d}else a=d/+k.Math.pow(2,-1074),c=+k.Math.floor(a),d=a-c,a=0,c=.5>d?c:.5<d?1+c:0!==c%2?1+c:c;c=+c;b=M(c|0,(b?-2147483648:0)|(a|0)<<20|c/4294967296|0)}b=b.s^b.q}return b;case "boolean":return a?1231:1237;case "undefined":return 0;default:return a&&a.$classData||
null===a?a.w():null===v?42:ha(a)}}var ha=null!==v?function(a){switch(typeof a){case "string":case "number":case "boolean":case "undefined":return ea(a);default:if(null===a)return 0;var b=v.get(a);void 0===b&&(u=b=u+1|0,v.set(a,b));return b}}:function(a){if(a&&a.$classData){var b=a.$idHashCode$0;if(void 0!==b)return b;if(k.Object.isSealed(a))return 42;u=b=u+1|0;return a.$idHashCode$0=b}return null===a?0:ea(a)};function A(a){return"number"===typeof a&&a<<24>>24===a&&1/a!==1/-0}
function C(a){return"number"===typeof a&&a<<16>>16===a&&1/a!==1/-0}function N(){this.t=this.B=void 0;this.i=this.l=this.f=null;this.k=0;this.A=null;this.p="";this.b=this.n=this.o=void 0;this.name="";this.isRawJSType=this.isArrayClass=this.isInterface=this.isPrimitive=!1;this.isInstance=void 0}function O(a,b,c){var d=new N;d.f={};d.l=null;d.A=a;d.p=b;d.b=function(){return!1};d.name=c;d.isPrimitive=!0;d.isInstance=function(){return!1};return d}
function P(a,b,c,d,h,g,l){var f=new N,n=aa(a);g=g||function(q){return!!(q&&q.$classData&&q.$classData.f[n])};l=l||function(q,G){return!!(q&&q.$classData&&q.$classData.k===G&&q.$classData.i.f[n])};f.t=h;f.f=c;f.p="L"+b+";";f.b=l;f.name=b;f.isInterface=!1;f.isRawJSType=!!d;f.isInstance=g;return f}
function ia(a){function b(f){if("number"===typeof f){this.z=Array(f);for(var n=0;n<f;n++)this.z[n]=h}else this.z=f}var c=new N,d=a.A,h="longZero"==d?Q().u:d;b.prototype=new R;b.prototype.constructor=b;b.prototype.$classData=c;d="["+a.p;var g=a.i||a,l=a.k+1;c.B=b;c.t=ja;c.f={a:1,V:1,c:1};c.l=a;c.i=g;c.k=l;c.A=null;c.p=d;c.o=void 0;c.n=void 0;c.b=void 0;c.name=d;c.isPrimitive=!1;c.isInterface=!1;c.isArrayClass=!0;c.isInstance=function(f){return g.b(f,l)};return c}
function y(a){if(!a.o){var b=new S;b.m=a;a.o=b}return a.o}N.prototype.getFakeInstance=function(){if(this===z)return"some string";if(this===I)return!1;if(this===B||this===D||this===E||this===F||this===H)return 0;if(this===da)return Q().u;if(this!==ca)return{$classData:this}};N.prototype.getSuperclass=function(){return this.t?y(this.t):null};N.prototype.getComponentType=function(){return this.l?y(this.l):null};
N.prototype.newArrayOfThisClass=function(a){for(var b=this,c=0;c<a.length;c++)b.n||(b.n=ia(b)),b=b.n;return x(b,a,0)};var ka=O(!1,"Z","boolean"),la=O(0,"C","char"),ma=O(0,"B","byte"),na=O(0,"S","short"),oa=O(0,"I","int"),pa=O("longZero","J","long"),qa=O(0,"F","float"),ra=O(0,"D","double");ka.b=w(ka);la.b=w(la);ma.b=w(ma);na.b=w(na);oa.b=w(oa);pa.b=w(pa);qa.b=w(qa);ra.b=w(ra);function T(){}function R(){}R.prototype=T.prototype;T.prototype.d=function(){return this};T.prototype.y=function(){var a=ba(this).m.name,b=(+(this.w()>>>0)).toString(16);return a+"@"+b};T.prototype.w=function(){return ha(this)};T.prototype.toString=function(){return this.y()};var ja=P({a:0},"java.lang.Object",{a:1},void 0,void 0,function(a){return null!==a},function(a,b){if(a=a&&a.$classData){var c=a.k||0;return!(c<b)&&(c>b||!a.i.isPrimitive)}return!1});T.prototype.$classData=ja;function U(){}
U.prototype=new R;U.prototype.constructor=U;U.prototype.d=function(){return this};function sa(a){a.getContext("2d");a.onmousedown=function(){};a.onmouseup=function(){};a.onmousemove=function(){}}U.prototype.main=function(a){sa(a)};U.prototype.$classData=P({F:0},"com.github.yuxiliu1995.wigner.poincare.JsExport$",{F:1,a:1});var V=void 0;function S(){this.m=null}S.prototype=new R;S.prototype.constructor=S;
S.prototype.y=function(){return(this.m.isInterface?"interface ":this.m.isPrimitive?"":"class ")+this.m.name};S.prototype.$classData=P({J:0},"java.lang.Class",{J:1,a:1});function L(){this.g=!1;this.C=this.r=this.j=null;this.v=!1;this.E=this.D=0}L.prototype=new R;L.prototype.constructor=L;
L.prototype.d=function(){K=this;this.j=(this.g=!!(k.ArrayBuffer&&k.Int32Array&&k.Float32Array&&k.Float64Array))?new k.ArrayBuffer(8):null;this.r=this.g?new k.Int32Array(this.j,0,2):null;this.g&&new k.Float32Array(this.j,0,2);this.C=this.g?new k.Float64Array(this.j,0,1):null;if(this.g)this.r[0]=16909060,a=1===((new k.Int8Array(this.j,0,8))[0]|0);else var a=!0;this.D=(this.v=a)?0:1;this.E=this.v?1:0;return this};L.prototype.$classData=P({P:0},"scala.scalajs.runtime.Bits$",{P:1,a:1});var K=void 0;
function J(){}J.prototype=new R;J.prototype.constructor=J;J.prototype.d=function(){return this};J.prototype.$classData=P({R:0},"scala.scalajs.runtime.RuntimeString$",{R:1,a:1});var fa=void 0;function W(){}W.prototype=new R;W.prototype.constructor=W;function ta(){}ta.prototype=W.prototype;var ca=P({S:0},"scala.runtime.BoxedUnit",{S:1,a:1,c:1},void 0,void 0,function(a){return void 0===a}),I=P({H:0},"java.lang.Boolean",{H:1,a:1,c:1,e:1},void 0,void 0,function(a){return"boolean"===typeof a});
function X(){this.u=null}X.prototype=new R;X.prototype.constructor=X;X.prototype.d=function(){Y=this;this.u=M(0,0);return this};
function ua(a,b){if(0===(-2097152&b))b=""+(4294967296*b+ +(a>>>0));else{var c=(32+t(1E9)|0)-(0!==b?t(b):32+t(a)|0)|0,d=c,h=0===(32&d)?1E9<<d:0;d=0===(32&d)?5E8>>>(31-d|0)|0|0<<d:1E9<<d;var g=a,l=b;for(a=b=0;0<=c&&0!==(-2097152&l);){var f=g,n=l,q=h,G=d;if(n===G?(-2147483648^f)>=(-2147483648^q):(-2147483648^n)>=(-2147483648^G))f=l,n=d,l=g-h|0,f=(-2147483648^l)>(-2147483648^g)?-1+(f-n|0)|0:f-n|0,g=l,l=f,32>c?b|=1<<c:a|=1<<c;c=-1+c|0;f=d>>>1|0;h=h>>>1|0|d<<31;d=f}c=l;if(0===c?-1147483648<=(-2147483648^
g):-2147483648<=(-2147483648^c))c=4294967296*l+ +(g>>>0),g=c/1E9,h=g/4294967296|0,d=b,b=g=d+(g|0)|0,a=(-2147483648^g)<(-2147483648^d)?1+(a+h|0)|0:a+h|0,g=c%1E9|0;c=""+g;b=""+(4294967296*a+ +(b>>>0))+"000000000".substring(c.length|0)+c}return b}X.prototype.$classData=P({Q:0},"scala.scalajs.runtime.RuntimeLong$",{Q:1,a:1,W:1,c:1});var Y=void 0;function Q(){Y||(Y=(new X).d());return Y}
var z=P({G:0},"java.lang.String",{G:1,a:1,c:1,U:1,e:1},void 0,void 0,function(a){return"string"===typeof a}),B=P({I:0},"java.lang.Byte",{I:1,h:1,a:1,c:1,e:1},void 0,void 0,function(a){return A(a)}),H=P({K:0},"java.lang.Double",{K:1,h:1,a:1,c:1,e:1},void 0,void 0,function(a){return"number"===typeof a}),F=P({L:0},"java.lang.Float",{L:1,h:1,a:1,c:1,e:1},void 0,void 0,function(a){return"number"===typeof a}),E=P({M:0},"java.lang.Integer",{M:1,h:1,a:1,c:1,e:1},void 0,void 0,function(a){return"number"===
typeof a&&(a|0)===a&&1/a!==1/-0}),da=P({N:0},"java.lang.Long",{N:1,h:1,a:1,c:1,e:1},void 0,void 0,function(a){return!!(a&&a.$classData&&a.$classData.f.x)}),D=P({O:0},"java.lang.Short",{O:1,h:1,a:1,c:1,e:1},void 0,void 0,function(a){return C(a)});function Z(){this.q=this.s=0}Z.prototype=new ta;Z.prototype.constructor=Z;Z.prototype.y=function(){Q();var a=this.s,b=this.q;return b===a>>31?""+a:0>b?"-"+ua(-a|0,0!==a?~b:-b|0):ua(a,b)};function M(a,b){var c=new Z;c.s=a;c.q=b;return c}
Z.prototype.w=function(){return this.s^this.q};Z.prototype.$classData=P({x:0},"scala.scalajs.runtime.RuntimeLong",{x:1,h:1,a:1,c:1,e:1});V||(V=(new U).d());m.Poincare=V;
}).call(this);
//# sourceMappingURL=wigner-opt.js.map
